### ISSUE TITLE
Enpty rows in progress.vsv

### ISSUE THREAD

**Issue by swdr1904** [DeepX-inc/machina#225]
progress.csv is one of  typical output files created by example codes of machina.
This output csv file has enpty rows.
To delete them, you can modify `machina/logger.py` as below.  
```python:machina/logger.py
def _add_output(file_name, arr, fds, mode='a'):
    if file_name not in arr:
        mkdir_p(os.path.dirname(file_name))
        arr.append(file_name)
        fds[file_name] = open(file_name, mode, newline='')  #'newline' is designated
```

**Comment by rarilurelo** [comment]
Could you tell us your environment information such as OS and version of python? And could you upload `progress.csv` created in your environment?

**Comment by swdr1904** [comment]
My envioment:
OS: windows10 (I recognize that windows is not supported by machina)
version: Python 3.6.5
It has no problem on macOS 10.14.4 with python 3.6.5.
I didin't check environment of ubuntu.

CSV file connot be upload directly on github issues, so the zipped file is uploaded.
[progress.csv.zip](https://github.com/DeepX-inc/machina/files/3036649/progress.csv.zip)

**Comment by rarilurelo** [comment]
I could confirm this error with windowsOS, and your suggestion has no influence on logs of csv with linuxOS and macOS. So could you send PR for this?

**Comment by swdr1904** [comment]
#234
