### ISSUE TITLE
Example script of DDPG seems incorrect

### ISSUE THREAD

**Issue by caprest** [DeepX-inc/machina#254]
In example of DDPG, default number of epochs to train policy/qfunc is set to number of steps collected in the iteration. (for example in default setting 50000) However, this seems to cause too long iteration without performance improvement. Is this an intended implementation or just a bug?

https://github.com/DeepX-inc/machina/blob/caf2e51859e764876963f8a24982607c0774e3b2/example/run_ddpg.py#L143-L148

Other implementation like spinning up seems to use total number of episode for updating. 
https://github.com/openai/spinningup/blob/master/spinup/algos/ddpg/ddpg.py

**Comment by rarilurelo** [comment]
In original paper of DDPG (https://arxiv.org/pdf/1509.02971.pdf), `Algorithm1 DDPG Algorithm` insists that a number of updating networks is as same as a number of steps. They updates network per step. To keep consistency with respect to the ratio of interaction times (a number of steps) to update times, we pass `step` to `epoch`.
